
api:
  key: '63NJUA45A97BF6OI'
  timeout: 3000

server:
  port: 8001


spring:
  application:
    name: Finance-crypto

  main:
    allow-bean-definition-overriding: true
  boot:
    admin:
      client:
        url: http://localhost:9090
        instance:
          management-url: http://localhost:9090/actuator
          health-url: http://localhost:9090/actuator/health
          service-url: http://localhost:9090

management:
  security:
    enabled: false
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
