
api:
  key: '63NJUA45A97BF6OI'
  timeout: 3000

server:
  port: 8001


spring:
  application:
    name: Finance-crypto

  data:
    mongodb:
      uri: mongodb+srv://financeclusteradmin:?DB12541@cluster0.z8e18.gcp.mongodb.net/finance_crypto?retryWrites=true&w=majority
      database: finance_crypto


  main:
    allow-bean-definition-overriding: true
  boot:
    admin:
      client:
        url: http://94.239.109.172:9090
        instance:
          management-url: http://94.239.109.172:9090/actuator
          health-url: http://94.239.109.172:9090/actuator/health
          service-url: http://94.239.109.172:9090

management:
  security:
    enabled: false
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
